name       : libcap-ng
version    : 0.7.8
release    : 1
source     :
    - https://people.redhat.com/sgrubb/libcap-ng/libcap-ng-0.7.8.tar.gz : c21af997445cd4107a55d386f955c5ea6f6e96ead693e9151277c0ab5f97d05f
license    : LGPL-2.1
component  : programming.library
summary    : Libcap-ng is a library that makes using posix capabilities easier
description: |
    The libcap-ng library should make programming with posix capabilities easier. The library has some utilities to help you analyse a system for apps that may have too much privileges.
setup      : |
    %configure --disable-static --with-python=no
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
