name       : libcap-ng
version    : 0.7.9
release    : 2
source     :
    - https://people.redhat.com/sgrubb/libcap-ng/libcap-ng-0.7.9.tar.gz : 4a1532bcf3731aade40936f6d6a586ed5a66ca4c7455e1338d1f6c3e09221328
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Libcap-ng is a library that makes using posix capabilities easier
description: |
    The libcap-ng library should make programming with posix capabilities easier. The library has some utilities to help you analyse a system for apps that may have too much privileges.
setup      : |
    %configure --disable-static --with-python=no
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
