name       : libcap-ng
version    : 0.8.3
release    : 10
source     :
    - https://github.com/stevegrubb/libcap-ng/archive/refs/tags/v0.8.3.tar.gz : e542e9139961f0915ab5878427890cdc7762949fbe216bd0cb4ceedb309bb854
license    : LGPL-2.1-or-later
component  : 
    - system.base
    - ^python-capng : programming.python
summary    :
    - Libcap-ng is a library that makes using posix capabilities easier
    - ^python-capng : Libcap-ng is a library that makes using posix capabilities easier - Python library
description: |
    The libcap-ng library should make programming with posix capabilities easier. The library has some utilities to help you analyse a system for apps that may have too much privileges.
builddeps  :
    - pkgconfig(libattr)
    - pkgconfig(python3)
    - swig
optimize   :
    - size
setup      : |
    %reconfigure --disable-static --with-python=no --with-python3
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
patterns:
    - ^python-capng:
        - /usr/lib/python3*
